
# Generated by Django 4.0.4 on 2022-08-16 16:58



from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),

                ('age', models.IntegerField(max_length=2)),
                ('size', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('accesories', models.CharField(max_length=255)),
                ('petowner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.user')),

               
            ],
        ),
    ]
