# Generated by Django 4.0.4 on 2022-08-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_age'),
        ('pets', '0003_alter_pet_user'),
    ]

    operations = [
    ]
