# Generated by Django 4.0.4 on 2022-08-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(max_length=15020),
        ),
    ]
