# Generated by Django 4.0.4 on 2022-08-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.IntegerField(choices=[(1, 'Dueño'), (2, 'Cuidador')], default=1),
        ),
    ]
