# Generated by Django 4.0.4 on 2022-08-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='precio'),
        ),
    ]
