# Generated by Django 4.0.4 on 2022-08-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitter', '0002_alter_sitter_picture_site_alter_sitter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='picture_site',
            field=models.ImageField(blank=True, default='', upload_to='sitter/static/img/'),
            preserve_default=False,
        ),
    ]
