# Generated by Django 4.0.4 on 2022-08-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitter', '0002_alter_sitter_descripcion_alter_sitter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitter',
            old_name='user_id',
            new_name='sitter_id',
        ),
    ]
