# Generated by Django 4.0.4 on 2022-08-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitter', '0002_alter_sitter_status'),
        ('sitter', '0003_alter_sitter_picture_site'),
    ]

    operations = [
    ]
