# Generated by Django 4.0.4 on 2022-08-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitter', '0004_merge_20220818_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='picture_site',
            field=models.ImageField(blank=True, upload_to='sitters/'),
        ),
    ]
