# Generated by Django 4.0.4 on 2022-08-26 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(auto_now_add=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('payment_type', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Tarjeta de crédito'), (3, 'Tarjeta de débito'), (4, 'Paypal')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'cancelar'), (2, 'confirmar')], default=2)),
                ('sitter_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitter.sitter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
