# Generated by Django 4.0.4 on 2022-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('adress_street', models.CharField(max_length=100)),
                ('adress_number', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=20)),
            ],
        ),
    ]
