# Generated by Django 4.0.4 on 2022-08-18 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitter', '0002_alter_sitter_descripcion_alter_sitter_user_id'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
